name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HTML and assets
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            **/*.html
            assets
          sparse-checkout-cone-mode: false
      - name: Remove .git
        run: rm -rf .git
      - name: Copy HTML and assets to server
        uses: appleboy/scp-action@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: .
          target: ~/tmp
